config/routes.rb
IntralistApp::Application.routes.draw do
  
  delete "user/authorizations/destroy", :to => "users/authorizations#destroy", :as => 'disconnect'

  devise_scope :user do
    get "/users/auth/:provider/callback", :to => "users/authorizations#create"
    get "/users/authorizations", :to => "users/authorizations#index"
  end

  get "unsubscribe", :to => "users/unsubscribe#unsubscribe"

  devise_for :users,
             :controllers => { :omniauth_callbacks => 'users/authorizations', :registrations => 'users/registrations'

                             },
             :path_names => { :sign_in => 'login', :sign_out => 'logout',
                              :password => 'secret', :confirmation => 'verification', :unlock => 'unblock',
                              :registration => 'register'}

  namespace :api, defaults: {format: :json} do
    resources :intralists, only: [:create, :show, :index]
    resources :items, only: [:create, :update, :destroy]
    resources :requests, only: [:index, :create, :show, :update, :destroy]
    resources :shares, only: :create
    resources :image_uploads, only: :create
    resources :lists, only: [:index, :create, :update, :destroy], module: 'lists' do
      resource :like, only: [:create]
      resources :bookmark, only: [:create, :destroy, :index]
      resources :items, only: [:create, :update, :destroy]
      resources :comments, only: [:index, :create, :update, :destroy]
      resources :copies, only: [:index]
      resources :requests
    end
    resources :users do
      resources :follows, only: [:index, :create, :destroy], :controller => "users/follows"
      resources :followers, only: [:index], :controller => "users/followers"
      resources :notifications, only: [:index, :destroy], :controller => "users/notifications"
      resource :profile, only: [:show, :edit, :update], :controller => "users/profile"
      resource :bookmarks, only: [:show], :controller => "users/bookmarks"
    end

    resources :list_groups, only: [:index, :show]

  end

  delete 'api/notifications', :to => "api/notifications#destroy"
  resource :search, :only => [:show], :controller => 'search'

  authenticated :user do
    root :to => "lists#index"
  end

  resources :users do
    resources :friends, :controller => 'users/friends' do
      collection do
        get :find_friends
      end
    end
  end
  resources :lists
  resources :requests

  # http://intralist.dev/users/aressidi/friends
  # http://intralist.dev/users/register/edit.aressidi
  # new_user_password
  # edit_user_password
  # edit_user_registration_path(current_user)

  #NOTE:  When deleting a comment off an intralist we need to pass
  #intralist=true, but DELETE doesn't support a request body.

  # Logout a user with just 'logout'
  # devise_scope :user do
    # get "/logout" => "devise/sessions#destroy"
  # end

  match '/api/lists/:list_id/comments/:id', :via => [:post], :controller => 'api/lists/comments', :action => 'destroy'
  match '/api/lists/unique_by_intralist', :via => [:post], :controller => 'api/lists/lists', :action => 'unique_by_intralist'
  match "*anything" => "lists#index"
  root :to => "lists#index"
end

app/views/shared/_facebook_javascript_sdk.html.erb
<% content_for :page_javascript do %>
  <script>
     var _FB_APP_ID = '<%= FACEBOOK_APP_ID %>';
  </script>
<% end %>

app/views/shared/_footer.html.haml
.container
  .body.span12
    %ul.pull-right
      %li= link_to 'Mobile', "/mobile"
      %li
        |
      %li= link_to 'About', "/about"
      %li
        |
      %li= link_to 'Privacy', "/privacy"
      %li
        |
      %li= link_to 'Advertising', "/advertising"
      %li
        |
      %li= link_to 'Terms', "/terms"
      %li
        |
      %li= link_to 'Help', "/help"

app/views/shared/_forgot_password_modal.html.haml
.center-block
  .row
    .col-xs-12.col-sm-6.col-md-12
      %p.header-message{:style => 'padding:5px;'}

      .center-block

        .pull-left{:style => "margin-left: 30px; width:80%"}
          = form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => {:class => "form-horizontal",
                                  :id => "forgot-password-modal"}) do |f|
            .form-group
              %label Email:
              = f.email_field :email, :class => "form-control"

            .form-group
              = f.submit "Send me reset password instructions", :class => 'btn btn-primary pull-right'

app/views/shared/_list_spacer.html.haml
.clear.clearfix.list-spacer{:style => "height: 20px"}
  &nbsp;

app/views/shared/_mix_panel.html.haml
/ start Mixpanel
:javascript
  (function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
  for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2-latest.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
  mixpanel.init("8af75ca3c02e1920924480dce8924e0c");
/ end Mixpanel

app/views/shared/_navbar.haml
#slide-nav.main-navbar.navbar.navbar-default.drop-shadow.navbar-fixed-top{role: "navigation", "ng-controller" => "NavBarCtrl"}
  .container
    .navbar-header
      %a.navbar-toggle{:style => "margin-right: 30px"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .logo
        = link_to(image_tag('intralist_logo_beta.png'), "/", :border => 0)
    #slidemenu
      .navbar-right
        - if user_signed_in?
          %ul.nav.navbar-nav.state-nav
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                = image_tag(has_profile_image?(current_user) ? current_user.profile.avatar : asset_path("annonymous_user.jpg"), :class => 'current-user-image float-left', :width => 30)
                %b.caret.float-left.current-user-image
              %ul.dropdown-menu
                %li
                  = link_to "My Profile", "/#{current_user.username}"
                //NOTE: Target self will force a full page reload
                %li
                  = link_to "Settings", edit_user_registration_path(current_user), :target => "_self"
                %li
                  = link_to "Connections", user_friends_path(current_user), :target => "_self"
                %li.divider
                %li
                  = link_to "Logout", destroy_user_session_path, :target => "_self"
        - else
          %ul.nav.navbar-nav
            %li
              %a.login-link{:data => {:toggle => "modal", :target => "#loginModal"}} Login
            %li
              %a.register-link{:data => {:toggle => "modal", :target => "#registerModal"}} Register
      %ul.nav.navbar-nav.menus
        %li.featured.dropdown
          = link_to "FEATURED", "#", :class => "dropdown-toggle menu-primary", :data => {:toggle => "dropdown"}
          %ul.dropdown-menu
            %li
              = link_to "Home", "/"
            %li
              = link_to "Trending", "/trending"
            %li
              = link_to "Best of", "/top"

        %li.discover.dropdown
          = link_to "DISCOVER", "#", :class => "dropdown-toggle menu-primary", :data => {:toggle => "dropdown"}
          %ul.dropdown-menu
            %li
              = link_to "My Feed", "/my-feed"
            %li
              = link_to "Recent", "/recent"
            %li
              = link_to "Intralists", "/intralists"
      .col-sm-3.col-md-4.col-lg-3.col-xl-3.pull-left
        %form.navbar-form{:role => "search", :id => 'primary-search', :action => "#{search_url}", :style => "margin-top: 12px;"}
          .form-group
            %input.form-control.search-input{type: "search", name: :q}
            %button.btn.btn-default.search-submit{type: "submit"}
              %i.glyphicon.glyphicon-search
      %ul.nav.navbar-nav.create-nav.navbar-right
        %li
          - if user_signed_in?
            %a{:href => "", "ng-click" => "toggleNewList()", :class => "create-link"} CREATE LIST
          - else
            %a{:href => "/users/login", :class => "create-link authenticate"} CREATE LIST
        %li
          - if user_signed_in?
            %a{"ng-click" => "toggleNewRequest()", "ng-show" => "!creatingRequest", :class => "create-link"} REQUEST LIST
          - else
            %a{:href => "/users/login", :class => "create-link authenticate"} REQUEST LIST
        - if user_signed_in?
          %li
            #user-notifications{:style => "margin-left: 15px; margin-right: 15px;"}
              - if current_user.notifications.count > 0
                %a{"data-toggle" => "dropdown", :role => "button"}
                  %span.glyphicon.glyphicon-bell{:style => "margin-top: 4px; font-size: 2em"}
                  - if current_user.notifications_count > 0
                    %span.badge.badge-important.notifications-indicator{:style => "position: absolute; top: -10px; right: 5px;"}= current_user.notifications_count
                .dropdown-menu{:role => "menu"}
                  = render :partial => 'shared/notifications', :locals => {:notifications => current_user.notifications}
                  .fixed-panel
                    = link_to "Clear Notifications", '', :class => 'clear-notifications'
              - else
                %span.glyphicon.glyphicon-bell{:style => "margin-top: 4px; font-size: 2em"}
#loginModal.modal.fade{:tabindex => "-1", :role => "dialog", "aria-labelledby" => "loginModalLabel", "aria-hidden" => true}
  .modal-dialog.modal-sm
    .modal-content
      .modal-header.pull-left{:style => "width: 100%"}
        %button.close{:type => "button", :data => {:dismiss => "modal"}, "aria-hidden" => "true"} &times;
        .pull-left 
          %h4.modal-title{:id => "loginModalLabel"} SIGN IN
        .pull-right{:style => "padding: 2px 10px 0 0"}
          %a.switch-reg{:href => "#"} create account
      .clear
      .modal-body
        = render :partial => "devise/sessions/form"
        
#registerModal.modal.fade{:tabindex => "-1", :role => "dialog", "aria-labelledby" => "registerModalLabel", "aria-hidden" => true}
  .modal-dialog.modal-md
    .modal-content
      .modal-header.pull-left{:style => "width: 100%"}
        %button.close{:type => "button", :data => {:dismiss => "modal"}, "aria-hidden" => "true"} &times;
        .pull-left
          %h4.modal-title{:id => "registerModalLabel"} SIGN UP
        .pull-right{:style => "padding: 2px 10px 0 0"}
          %a.switch-login{:href => "#"} ...or login
      .clear
      .modal-body
        = render :partial => "users/registrations/form"

#completeRegistrationModal.modal.fade{:tabindex => "-1", :role => "dialog", "aria-labelledby" => "completeRegistrationModalLabel", "aria-hidden" => true}
  .modal-dialog.modal-md
    .modal-content
      .modal-header.pull-left{:style => "width: 100%"}
        %button.close{:type => "button", :data => {:dismiss => "modal"}, "aria-hidden" => "true"} &times;
        .pull-left
          %h4.modal-title{:id => "completeRegistrationModalLabel"} Complete Registration
      .clear
      .modal-body
        = render :partial => "users/registrations/complete_facebook_registration"

#forgotPasswordModal.modal.fade{:tabindex => "-1", :role => "dialog", "aria-labelledby" => "forgotPasswordModalLabel", "aria-hidden" => true}
  .modal-dialog.modal-md
    .modal-content
      .modal-header.pull-left{:style => "width: 100%"}
        %button.close{:type => "button", :data => {:dismiss => "modal"}, "aria-hidden" => "true"} &times;
        .pull-left
          %h4.modal-title{:id => "forgotPasswordLabel"} Forgot your password?
        .pull-right{:style => "padding: 2px 10px 0 0"}
          %a.switch-login{:href => "#", :id => 'back-to-login'} Back to login
      .clear
      .modal-body
        = render :partial => "shared/forgot_password_modal"


= render :partial => 'shared/facebook_javascript_sdk'

app/views/shared/_notifications.html.haml
.notifications-list
  - notifications.group_by {|g| g.group_type}.each do |g, n|
    - unless g.nil?
      .header.pull-left= g.pluralize.upcase
      / .smaller.pull-right
      /         = link_to "clear", "javascript:;", :data => {:group => g}, :class => "clear-group"
      .clear{:style => "height: 5px"}
    - n.each do |n|
      .media{:class => "#{'read-notification' if current_user.last_notification_id >= n._id rescue nil}", :data => {"notification-id" => n._id}}
        .pull-left
          = image_tag n.image ? n.image : asset_path("annonymous_user.jpg"), :class => 'media-object img-polaroid', :width => 35
        .media-body
          = n.body.html_safe
          %span.timestamp= distance_of_time_in_words_to_now(n.created_at)

app/views/shared/_profile_image.html.haml
.img-polaroid
  %a{:href => "#{user_path(user)}"}
    / .media-object.profile-image{:style => "background: url(#{has_profile_image?(user) ? user.profile.avatar : asset_path('annonymous_user.jpg')}); background-size: 35px auto; width: 35px; height: 35px;"}
    .media-object.profile-image
      = image_tag has_profile_image?(user) ? user.profile.avatar : asset_path('annonymous_user.jpg'), :height => 35, :width => 35

app/views/shared/_user.html.haml
.media
  .pull-left
    %a{:href => user_path(user)}
      = render :partial => "shared/profile_image", :locals => {:user => user}
  .media-body
    .media-heading
      .span3
        .pull-left= link_to user.username, user_path(user.username)
        .pull-left.smaller{:style => "padding-left: 10px"}
          %i registered on: #{user.created_at.strftime("%m/%d/%y")}
        %br
        .clearfix
          Number of lists: #{link_to user.lists.count, user_profile_path(user)}
      .span2
        - if follows?(user)
          = button_to "unfollow", unfollow_user_path(user), :method => 'delete', :form => {:id => 'unfollow_form'}, remote: true, :class => 'btn', :id => 'unfollow', :name => 'unfollow_button', "data-list-creator-id" => "#{user.id}"
        - else
          = button_to "follow", follow_user_path(user), remote: true, :form => {:id => 'follow_form'}, :class => 'btn', :id => 'follow', :name => 'follow_button', "data-list-creator-id" => "#{user.id}"